Cherry pick of b1cf365081bb7f43204afc83233a6d6fd9da692a failed
stdout:
CONFLICT (modify/delete): account_multic_fix/models/account_move.py deleted in HEAD and modified in b1cf365 ([FIX] Fix move tax recomputation on change company). Version b1cf365 ([FIX] Fix move tax recomputation on change company) of account_multic_fix/models/account_move.py left in tree.

stderr:
08:52:53.142630 git.c:444               trace: built-in: git cherry-pick b1cf365081bb7f43204afc83233a6d6fd9da692a
error: could not apply b1cf365... [FIX] Fix move tax recomputation on change company
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: